"""
Per-case failure diagnosis for the independent field benchmark.

Regenerates `results/field_failure_analysis.md` from live reasoner output, so that
every figure in the report is traceable to a run rather than hand-written prose.

Each in-scope (positive) case is assigned exactly one failure cause:

  resolved              - RiceKG predicts the true label.
  vocabulary_gating     - No recorded symptom maps into `model.ALL_SYMPTOMS`; the
                          reasoner receives an empty assertion set and cannot fire.
  partial_vocabulary    - Some symptoms map, some do not, and no rule fires. The
                          dropped descriptors are candidates for ontology extension.
  rule_recall_failure   - Every recorded symptom maps, yet no Tier-1 or Tier-2 rule
                          fires. This is a rule-coverage defect, not a vocabulary gap.
  misfire               - A rule fires but asserts a threat other than the true label.

Usage:  python analysis/field_failure_analysis.py
"""
import csv
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import model  # noqa: E402

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIELD_CSV = os.path.join(BASE_DIR, "data", "benchmark_field.csv")
MAPPING_CSV = os.path.join(BASE_DIR, "data", "symptom_mapping.csv")
OUT_MD = os.path.join(BASE_DIR, "results", "field_failure_analysis.md")

SYM_COLS = [f"symptom_{i}" for i in range(1, 7)]


def load_cases(split="all"):
    with open(FIELD_CSV, newline="") as fh:
        cases = list(csv.DictReader(fh))
    if split and split != "all":
        cases = [c for c in cases if c.get("split", "dev") == split]
    return cases


def load_mapping():
    with open(MAPPING_CSV, newline="") as fh:
        return list(csv.DictReader(fh))


def classify(mapped, unmapped, predicted, expected):
    if set(predicted) == set(expected):
        return "resolved"
    if predicted:
        return "misfire"
    if not mapped:
        return "vocabulary_gating"
    if unmapped:
        return "partial_vocabulary"
    return "rule_recall_failure"


def main(split="all"):
    cases = load_cases(split=split)
    mapping = load_mapping()

    n_total = len(cases)
    positives = [c for c in cases if c["diagnosis"] != "No_Diagnosis"]
    negatives = [c for c in cases if c["diagnosis"] == "No_Diagnosis"]

    n_mapped_terms = sum(1 for m in mapping if m["decision"] == "mapped")
    n_unmapped_terms = sum(1 for m in mapping if m["decision"] == "unmapped")

    rows = []
    for c in positives:
        mapped = [c[k].strip() for k in SYM_COLS if c[k].strip()]
        unmapped = [t for t in c.get("unmapped_terms", "").split(";") if t]
        expected = [t.strip() for t in c["diagnosis"].split(" and ") if t.strip()]

        graded = model.predict_diseases(mapped) if mapped else []
        predicted = [g["threat"] for g in graded]
        fired = sorted({r for g in graded for r in g["fired_rules"]})
        missing = sorted({s for g in graded for s in g["missing_symptoms"]})

        rows.append({
            "case": c,
            "mapped": mapped,
            "unmapped": unmapped,
            "expected": expected,
            "predicted": predicted,
            "graded": graded,
            "fired": fired,
            "missing": missing,
            "cause": classify(mapped, unmapped, predicted, expected),
        })

    # False positives on the negative controls
    false_positives = []
    for c in negatives:
        mapped = [c[k].strip() for k in SYM_COLS if c[k].strip()]
        if not mapped:
            continue
        pred = model.predict_diseases_flat(mapped)
        if pred:
            false_positives.append((c["case_id"], pred))

    n_resolved = sum(1 for r in rows if r["cause"] == "resolved")

    L = []
    split_title = f" ({split.upper()} Split)" if split != "all" else ""
    L.append(f"# Per-Case Failure Diagnosis: Positive Field Benchmark Cases{split_title}")
    L.append("")
    L.append(f"> **Generated by**: `analysis/field_failure_analysis.py` (live reasoner output).  ")
    split_str = f"split `{split}`" if split != "all" else "all splits"
    L.append(f"> **Benchmark**: `data/benchmark_field.csv` ({split_str}) — {n_total} cases: "
             f"{len(positives)} in-scope disease cases, {len(negatives)} out-of-scope negative controls.  ")
    L.append(f"> **Positive-case recall**: **{n_resolved}/{len(positives)}** "
             f"({100.0 * n_resolved / len(positives):.1f}%).")
    L.append("")
    L.append("## Identifier normalization")
    L.append("")
    L.append("Symptom identifiers in this benchmark were originally recorded in a descriptive "
             "snake_case namespace (`seed_yellowish_green_velvety_balls`) that shares no terms with the "
             "ontology vocabulary `model.ALL_SYMPTOMS` (`Rusty_Grain_Balls`). None of the 25 recorded "
             "descriptors matched, so every case reached the reasoner as an empty assertion set and the "
             "benchmark could not exercise the rule base at all. `data/symptom_mapping.csv` records the "
             f"resolution of each descriptor: **{n_mapped_terms} mapped** to an ontology term and "
             f"**{n_unmapped_terms} left unmapped** because the ontology models no corresponding concept. "
             "The unmapped descriptors are retained per case in the `unmapped_terms` column so the "
             "vocabulary gap stays auditable.")
    L.append("")
    L.append("## Failure causes")
    L.append("")
    L.append("| Cause | Meaning | Remedy |")
    L.append("|:--|:--|:--|")
    L.append("| `resolved` | RiceKG predicts the true label. | — |")
    L.append("| `vocabulary_gating` | No symptom maps; reasoner receives an empty input. | Ontology extension |")
    L.append("| `partial_vocabulary` | Some symptoms map, some dropped, no rule fires. | Ontology extension |")
    L.append("| `rule_recall_failure` | All symptoms map, yet no rule fires. | Rule revision |")
    L.append("| `misfire` | A rule fires on the wrong threat. | Rule revision |")
    L.append("")
    L.append("## Summary matrix")
    L.append("")
    L.append("| Case | Split | True Label | Mapped Symptoms | Dropped Descriptors | Rules Fired | Predicted | Cause |")
    L.append("|:--|:--|:--|:--|:--|:--|:--|:--|")
    for r in rows:
        L.append(
            f"| **{r['case']['case_id']}** | `{r['case'].get('split', '?')}` | `{r['case']['diagnosis']}` "
            f"| {', '.join(f'`{s}`' for s in r['mapped']) or '*none*'} "
            f"| {', '.join(f'`{s}`' for s in r['unmapped']) or '*none*'} "
            f"| {', '.join(r['fired']) or '*none*'} "
            f"| {', '.join(r['predicted']) or '`No_Diagnosis`'} "
            f"| **`{r['cause']}`** |"
        )
    L.append("")
    L.append("## Per-case detail")
    L.append("")
    for r in rows:
        c = r["case"]
        L.append(f"### {c['case_id']} — `{c['diagnosis']}`")
        L.append("")
        L.append(f"- **Source**: {c.get('citation', '').strip() or 'n/a'}")
        if c.get("doi", "").strip():
            L.append(f"- **DOI**: [{c['doi'].strip()}](https://doi.org/{c['doi'].strip()})")
        L.append(f"- **Verbatim symptom text**: \"{c.get('raw_symptom_text', '').strip()}\"")
        L.append(f"- **Mapped into ontology**: {', '.join(f'`{s}`' for s in r['mapped']) or '*none*'}")
        L.append(f"- **Dropped (no ontology term)**: {', '.join(f'`{s}`' for s in r['unmapped']) or '*none*'}")
        if r["graded"]:
            for g in r["graded"]:
                L.append(f"- **Inferred**: `{g['threat']}` (grade `{g['grade']}`, "
                         f"confidence {g['confidence']:.4f}, antecedent coverage "
                         f"{g['antecedent_coverage']:.4f}) via {', '.join(g['fired_rules'])}")
        else:
            L.append("- **Inferred**: no threat; reasoner returned `No_Diagnosis`")
        if r["missing"]:
            L.append(f"- **Unmet antecedents**: {', '.join(f'`{s}`' for s in r['missing'])}")
        L.append(f"- **Failure cause**: **`{r['cause']}`**")
        L.append("")

    L.append("## Negative controls")
    L.append("")
    if false_positives:
        L.append(f"{len(false_positives)} of {len(negatives)} negative controls produced a false positive:")
        L.append("")
        for cid, pred in false_positives:
            L.append(f"- `{cid}` -> {', '.join(pred)}")
    else:
        L.append(f"None of the {len(negatives)} out-of-scope negative controls produced a false positive. "
                 "Note that this specificity is only partly earned: cases whose descriptors are entirely "
                 "unmapped cannot fire a rule regardless of their content, so rejection is guaranteed by "
                 "construction rather than by discrimination.")
    L.append("")

    with open(OUT_MD, "w", newline="", encoding="utf-8") as fh:
        fh.write("\n".join(L) + "\n")

    print(f"[OUTPUT] {OUT_MD}")
    print(f"positive-case recall: {n_resolved}/{len(positives)}")
    for r in rows:
        print(f"  {r['case']['case_id']:<9} {r['cause']}")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Per-case field failure analysis by split.")
    parser.add_argument("--split", choices=["dev", "eval", "all"], default="all",
                        help="Dataset split to evaluate (default: all).")
    args = parser.parse_args()
    main(split=args.split)
