import os
import re

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPORT = os.path.join(BASE_DIR, "results", "REPORT.md")

# (key, section title in the table of contents); the key is also the link anchor.
SECTIONS = [
    ("results-index", "Results index (claim, command, source, value)"),
    ("kb-verification", "Knowledge-base verification"),
    ("competency-questions", "Ontology competency questions"),
    ("graded-evaluation", "Graded case-level evaluation (field benchmark)"),
    ("field-failure-analysis", "Per-case field failure diagnosis"),
    ("ablation", "Ablation of the architecture"),
    ("baselines", "Baseline comparison (5x2-fold protocol)"),
    ("top-k", "Top-k differential diagnosis"),
    ("degradation-curve", "Observation occlusion degradation"),
    ("learning-curve", "Cold-start learning curve"),
    ("probabilistic", "Probabilistic (noisy-OR) layer"),
    ("expert-validation", "Expert-based validation"),
    ("holdout-archived", "Archived: locked holdout run (commit 385caf9)"),
]
_KEYS = [k for k, _ in SECTIONS]
_BLOCK = re.compile(r'<a id="([a-z0-9-]+)"></a>\n(.*?)\n<!-- end:\1 -->\n', re.S)

HEADER = [
    "# RiceKG Results",
    "",
    "Generated by the scripts in `analysis/` and `baselines/`; each section is rewritten by the script "
    "that produces it (the [results index](#results-index) gives the command behind every figure). Structured "
    "data for each section is in the matching `results/*.json`.",
    "",
]


def _demote(md):
    # Shift every heading down one level so each script's "# Title" becomes a section heading.
    out, fenced = [], False
    for line in md.rstrip("\n").split("\n"):
        if line.startswith("```"):
            fenced = not fenced
        out.append("#" + line if (not fenced and line.startswith("#")) else line)
    return "\n".join(out)


def read_sections(path=REPORT):
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as f:
        return {m.group(1): m.group(2) for m in _BLOCK.finditer(f.read())}


def read_section(key, path=REPORT):
    # Section body as written by write_section (headings demoted), or "" if absent.
    return read_sections(path).get(key, "")


def write_section(key, markdown, path=REPORT, demote=True):
    if key not in _KEYS:
        raise KeyError(f"unknown report section {key!r}; add it to analysis/report.SECTIONS")
    sections = read_sections(path)
    sections[key] = _demote(markdown) if demote else markdown.rstrip("\n")
    lines = HEADER + ["## Contents", ""]
    lines += [f"- [{title}](#{k})" for k, title in SECTIONS if k in sections]
    lines += ["", "---", ""]
    for k in _KEYS:
        if k in sections:
            lines += [f'<a id="{k}"></a>', sections[k], f"<!-- end:{k} -->", ""]
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    return path
